name: SUPER ULTRA MEGA COOL PLUGIn
version: 1.163
author: Justix
main: net.dev.nickplugin.main.Main
description: This plugin allows you to change your identity (skin, name, nametag, tabname, chatname)
website: https://www.spigotmc.org/resources/eazynick-autonicksystem-api-src-bungeecord-multiworld-1-7-10-1-13-1.51398/
api-version: 1.13

commands:
      nick:
        description: Changes your identity(skin, name, nametag, tabname, chatname)
        aliases:
        - d
        - disguise
      unnick:
        description: Resets your complete identity
        aliases:
        - ud
        - undisguise
      realname:
        description: Shows the real name of a nicked player
        aliases:
        - rd
        - realdisguise
      nickgui:
        description: Opens a little gui to change/reset your identity
        aliases:
        - dgui
        - disguisegui
      nickother:
        description: Changes/Resets the identity of other players
        aliases:
        - do
        - disguiseother
      changeskin:
        description: Changes your skin
      changename:
        description: Changes your name
      resetskin:
        description: Resets your skin
      resetname:
        description: Resets your name
      nicklist:
        description: Opens a GUI with all random nicknames
        aliases:
        - dlist
        - disgusielist
      bookgui:
        description: Opens a Nick-GUI like HyPixel.net
      booknick:
        description: This command is only for the plugin, you do not require to know for what this is
      reloadconfig:
        description: Reloads the configuration file
        aliases:
        - reloadcfg
        - rconfig
      fixskin:
        description: Fixes your skin, if it was not loaded correctly
      renick:
        description: This command is only for the plugin, you do not require to know for what this is
      name:
        description: Shows your active nickname
      nickedplayers:
        description: Shows a list of all players, who are currently nicked
      eazynick:
        description: Shows some informations of the plugin/a list of commands
      nickupdatecheck:
        description: Checks for updates of the plugin
      togglebungeenick:
        description: Toggles the automatic nickname on server switch
        aliases:
        - togglenick
        - togglebungeedisguise
        - toggledisguise
